In [1]:
import numpy as np
import scipy

In [ ]:
A = np.array([[3,-2,5], [1,0,2], [4,1,-1]])
B = np.array([[2 ,-1 ,3], [-3,0,-4], [1,2,-2]])

AB = A@B
BA = B@A

display(AB, BA)

np.array_equal(AB, BA)

array([[17,  7,  7],
       [ 4,  3, -1],
       [ 4, -6, 10]])

array([[ 17,  -1,   5],
       [-25,   2, -11],
       [ -3,  -4,  11]])

False

In [ ]:
C = np.array([[4,2,3],[3,1,1],[2,5,7]])
detC = np.linalg.det(C)
traceC = np.trace(C)

display(detC, traceC)

matrix_is_invertible = detC != 0
display(matrix_is_invertible)


8.999999999999998

12

True

In [ ]:
Q = np.random.randint(-10, 10, (3,3))
display(Q)

Q_is_orthogonal = np.array_equal( Q.T @ Q , np.eye(3) )
display(Q_is_orthogonal)

array([[ -3, -10,  -2],
       [ -4,   3,  -8],
       [ -5,   9,   7]])

False

In [ ]:
inverse_Q = np.linalg.inv(Q)
display(inverse_Q)

array([[ 0.11159737,  0.07658643, -0.12253829],
       [-0.08315098, -0.09628009, -0.04595186],
       [-0.04376368,  0.10722101,  0.02844639]])

### Section 2

In [ ]:
D = np.array([[1,2,3],[0,1,4],[5,6,0]])
inverse_D = np.linalg.inv(D)
display(inverse_D)

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [ ]:
display(inverse_D@D)
np.array_equal( inverse_D@D , np.eye(3) )

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -8.8817842e-16,  1.0000000e+00]])

False

A square matrix A is diagonalizable if it can be expressed in the form:
A = PDP^−1

- P is a matrix whose columns are the eigenvectors of A.

- D is a diagonal matrix whose diagonal entries are the eigenvalues of A.

In [ ]:
def can_be_diagonalized(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    print("eigenvectors:\n",eigenvectors)
    D = np.diag(eigenvalues)
    print("eigen_vals:\n", D)
    inverse_P = np.linalg.inv(eigenvectors)
    print("inverse_P:\n", inverse_P)
    return np.allclose(A, eigenvectors@D@inverse_P)

print(can_be_diagonalized(D))

eigenvectors:
 [[ 0.22578016 -0.75769839 -0.49927017]
 [ 0.52634845  0.63212771 -0.46674201]
 [-0.81974424 -0.16219652 -0.72998712]]
eigen_vals:
 [[-5.2296696   0.          0.        ]
 [ 0.         -0.02635282  0.        ]
 [ 0.          0.          7.25602242]]
inverse_P:
 [[ 0.58487594  0.51408004 -0.72871678]
 [-0.83497187  0.62509972  0.17139515]
 [-0.47126744 -0.71618133 -0.58965193]]
True


### section 3

In [2]:
E = np.array([[4,1,-2],[2,3,1],[-1,0,2]])
print(E)

print(can_be_diagonalized(E))

[[ 4  1 -2]
 [ 2  3  1]
 [-1  0  2]]


NameError: name 'can_be_diagonalized' is not defined

ing the eigenvalues and eigenvectors from question 5, calculate the matrix exponential exp(E) = P exp(D)P
−1 using NumPy. Compare your
result with the built-in matrix exponential function (scipy.linalg.expm)
and verify that both results match.


In [3]:
eigenresults_of_E = np.linalg.eig(E)
D_of_E = np.diag( eigenresults_of_E.eigenvalues )
exp_D_of_E = np.exp(D_of_E)
eigenvectors_E = eigenresults_of_E.eigenvectors

print(D_of_E)
print(eigenvectors_E)
exp_E = eigenvectors_E @ exp_D_of_E @ np.linalg.inv(eigenvectors_E)
print(exp_E)

[[5.33005874 0.         0.        ]
 [0.         0.87158094 0.        ]
 [0.         0.         2.79836032]]
[[-0.78511665 -0.52528701 -0.24761959]
 [-0.57271805  0.71230384  0.91786992]
 [ 0.23576661 -0.46550704  0.3101602 ]]
[[144.52851872  57.07220462 -70.84247477]
 [ 98.97988566  54.38181333 -32.87710134]
 [-42.82730498 -15.15972161  26.3481609 ]]


In [5]:
scipy.linalg.expm(E)

array([[143.12747994,  57.90613804, -70.20397698],
       [100.60950971,  54.81580916, -33.31046017],
       [-42.70337167, -15.20276637,  27.31520386]])